---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app govee2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: govee2mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GOVEE_EMAIL: "{{ .GOVEE_EMAIL }}"
        GOVEE_PASSWORD: "{{ .GOVEE_PASSWORD }}"
        GOVEE_API_KEY: "{{ .GOVEE_API_KEY }}"
        GOVEE_MQTT_USER: "{{ .X_EMQX_MQTT_USERNAME }}"
        GOVEE_MQTT_PASSWORD: "{{ .X_EMQX_MQTT_PASSWORD }}"
  dataFrom:
    - extract:
        key: emqx
    - extract:
        key: govee2mqtt
