---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homerp
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr-docker-secret
      automountServiceAccountToken: false
      enableServiceLinks: false

    controllers:
      backend:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: *app
                      app.kubernetes.io/controller: backend
                  topologyKey: kubernetes.io/hostname

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "18"
            envFrom:
              - secretRef:
                  name: homerp-initdb-secret

        containers:

          app:
            image:
              repository: ghcr.io/mchestr/homerp/backend
              tag: latest@sha256:e2f10a815ea14f3b53d3cf979510455154b0a422e81a60833ffcf5fc41b01066
            env:
              DEBUG: "false"
              UPLOAD_DIR: /app/uploads
              FRONTEND_URL: &url https://homerp.xyz
              REDIS_URL: redis://homerp-dragonfly.default.svc.cluster.local:6379
              ALLOWED_NETWORKS: "10.0.20.200/32"
              FREE_MONTHLY_CREDITS: "10"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: homerp-pguser-secret
                    key: async_uri
            envFrom:
              - secretRef:
                  name: homerp-secret
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

      frontend:
        replicas: 3
        strategy: RollingUpdate
        rollingUpdate:
          unavailable: 1
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: *app
                      app.kubernetes.io/controller: frontend
                  topologyKey: kubernetes.io/hostname
        containers:
          app:
            image:
              repository: ghcr.io/mchestr/homerp/frontend
              tag: latest@sha256:a1f53ff45f909a3fb67d001dce14a2f15f5bdb4d0596f134c52ef4dd9f17dd47
            env:
              NEXT_PUBLIC_API_URL: *url
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      backend:
        controller: backend
        ports:
          http:
            port: &backendPort 8000
      frontend:
        controller: frontend
        ports:
          http:
            port: &frontendPort 3000

    route:
      app:
        hostnames:
          - homerp.xyz
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /api
            backendRefs:
              - name: homerp-backend
                port: *backendPort
          - backendRefs:
              - name: homerp-frontend
                port: *frontendPort

    persistence:
      uploads:
        type: nfs
        server: nebula.chestr.dev
        path: /var/nfs/shared/cluster/apps/homerp/uploads
        globalMounts:
          - path: /app/uploads
