---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homerp
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: gitlab-docker-secret
      automountServiceAccountToken: false
      enableServiceLinks: false

    controllers:
      backend:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: *app
                        app.kubernetes.io/controller: backend
                    topologyKey: kubernetes.io/hostname

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "18"
            envFrom:
              - secretRef:
                  name: homerp-initdb-secret

        containers:

          app:
            image:
              repository: registry.gitlab.com/mchestr/homerp/backend
              tag: latest@sha256:797b8d6ecbbe7256b3947acb192f6ff0139fbd2a865b7ffdcb0670c732406fce
            env:
              DEBUG: "false"
              UPLOAD_DIR: /app/uploads
              FRONTEND_URL: &url https://homerp.xyz
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: homerp-pguser-secret
                    key: async_uri
            envFrom:
              - secretRef:
                  name: homerp-secret
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

      frontend:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: *app
                        app.kubernetes.io/controller: frontend
                    topologyKey: kubernetes.io/hostname
        containers:
          app:
            image:
              repository: registry.gitlab.com/mchestr/homerp/frontend
              tag: latest@sha256:2451e6703f04ed6203d6c77ed430f2908339e8aa1bc79174c99166e68c2f8201
            env:
              NEXT_PUBLIC_API_URL: *url
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      backend:
        controller: backend
        ports:
          http:
            port: &backendPort 8000
      frontend:
        controller: frontend
        ports:
          http:
            port: &frontendPort 3000

    route:
      app:
        hostnames:
          - homerp.xyz
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /api
            backendRefs:
              - name: homerp-backend
                port: *backendPort
          - backendRefs:
              - name: homerp-frontend
                port: *frontendPort

    persistence:
      uploads:
        type: nfs
        server: nebula.chestr.dev
        path: /var/nfs/shared/cluster/apps/homerp/uploads
        globalMounts:
          - path: /app/uploads
