---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellyfin-restic
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: jellyfin-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY_BUCKET }}/jellyfin"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-restic
    - extract:
        key: backblaze
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyfin
  namespace: default
spec:
  sourcePVC: config-jellyfin-0
  trigger:
    schedule: "0 9 * * *"
  restic:
    repository: jellyfin-restic-secret
    copyMethod: Snapshot
    pruneIntervalDays: 10
    cacheCapacity: 8Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    retain:
      daily: 7
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
