---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster17.yaml
  - ./homerp.yaml
  - ./immich.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
  - ./service.yaml
