---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app subs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: subs-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        PLEX_CLIENT_IDENTIFIER: "{{ .PLEX_CLIENT_IDENTIFIER }}"
        DISCORD_BOT_TOKEN: "{{ .MIKEFLIX_APPLICATION_BOT_TOKEN }}"
        DISCORD_SUPPORT_CHANNEL_ID: "{{ .DISCORD_SUPPORT_CHANNEL_ID }}"
  dataFrom:
    - extract:
        key: *app
    - extract:
        key: discord-mflix
