---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${APP}-initdb"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-initdb-secret"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: ${APP}
        INIT_POSTGRES_HOST: ${CNPG_NAME:=postgres17}-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: '{{ index . "${APP}_postgres_username" }}'
        INIT_POSTGRES_PASS: '{{ index . "${APP}_postgres_password" }}'
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-pguser"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-pguser-secret"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        port: "5432"
        host: ${CNPG_NAME:=postgres17}-rw.database.svc.cluster.local
        ro_host: ${CNPG_NAME:=postgres17}-ro.database.svc.cluster.local
        user: '{{ index . "${APP}_postgres_username" }}'
        password: '{{ index . "${APP}_postgres_password" }}'
        db: "${APP}"
        uri: 'postgresql://${APP}:{{ index . "${APP}_postgres_password" }}@${CNPG_NAME:=postgres17}-rw.database.svc.cluster.local:5432/${APP}'
        async_uri: 'postgresql+asyncpg://${APP}:{{ index . "${APP}_postgres_password" }}@${CNPG_NAME:=postgres17}-rw.database.svc.cluster.local:5432/${APP}'
        dsn: 'host=${CNPG_NAME:=postgres17}-rw.database.svc.cluster.local port=5432 user={{ index . "${APP}_postgres_username" }} password={{ index . "${APP}_postgres_password" }} dbname=${APP} sslmode=disable'
  dataFrom:
    - extract:
        key: cloudnative-pg
