---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: minio
        group: internal
        interval: 1h
        url: https://minio.chestr.dev
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
      - name: minio
        group: guarded
        interval: 1h
        url: 1.1.1.1
        dns:
          query-name: minio.chestr.dev
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover
