---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: victoria-metrics-dashboard
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: victoriametrics.png
    gethomepage.dev/name: VictoriaMetrics
    gethomepage.dev/group: Observability
spec:
  hostnames: ["vm.chestr.dev"]
  parentRefs:
    - name: internal
      namespace: networking
      sectionName: https
  rules:
    - backendRefs:
        - name: vmsingle-stack
          namespace: observability
          port: 8429
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vmalertmanager
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: alertmanager.png
    gethomepage.dev/name: AlertManager
    gethomepage.dev/group: Observability
spec:
  hostnames: ["am.chestr.dev"]
  parentRefs:
    - name: internal
      namespace: networking
      sectionName: https
  rules:
    - backendRefs:
        - name: vmalertmanager-stack
          namespace: observability
          port: 9093
