---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./dashbrr/ks.yaml
  - ./displex/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyplex-watched/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./jellystat/ks.yaml
  - ./maintainerr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./unpackerr/ks.yaml
  - ./wizarr/ks.yaml
