---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploykey.sops.yaml
  - helm-release.yaml
  - pvc.yaml
  - secret.sops.yaml
patchesStrategicMerge:
  - patches/postgres-init.yaml
