---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app saidcompany
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: saidcompany-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        API_KEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: *app
