---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cyberpower-ups.yaml
  - espressif-esp32.yaml
  - google-coral.yaml
  - intel-gpu.yaml
  - nvidia-gpu.yaml
  - zigbee.yaml
  - zwave.yaml
