---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app plex-wrapped
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plex-wrapped-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        PLEX_CLIENT_IDENTIFIER: "{{ .PLEX_CLIENT_IDENTIFIER }}"
  dataFrom:
    - extract:
        key: *app
