---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-loadbalancer-ip-main
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/role: worker
  virtualRouters:
    - localASN: 64512
      exportPodCIDR: false
      serviceSelector: # this replaces address-pools, instead of defining the range of IPs that can be assigned to LoadBalancer services, now services have to match below selectors for their LB IPs to be announced
        matchExpressions:
          - key: thisFakeSelector
            operator: NotIn
            values: ["will-match-and-announce-all-services"]
      neighbors:
        - peerAddress: "192.168.1.1/32" # unlike bgp-config ConfigMap, peerAddress needs to be in CIDR notation
          peerASN: 64512
