---
libraries:
  Movies:
    collection_files:
      - file: config/1-moviecharts.yml
      - file: config/3-bestof.yml
      - file: config/5-holiday.yml
    overlay_files:
      - default: ribbon
      - default: ratings
      - default: resolution
      - default: streaming
    operations:
      mass_genre_update: imdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_metacritic
      mass_user_rating_update: imdb

  TV Shows:
    collection_files:
      - file: config/2-tvcharts.yml
      - file: config/7-networks.yml
    overlay_files:
      - default: ribbon
      - default: ratings
      - default: resolution
      - default: streaming
      - default: status
    operations:
      mass_genre_update: tmdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_metacritic
      mass_user_rating_update: imdb

settings:
  cache: true
  cache_expiration: 60
  asset_folders: false
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 1
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: false
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: false
  save_report: false
  tvdb_language: eng
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_report: false
  verify_ssl: true
  check_nightly: false
  show_unconfigured: true
  run_order:
    - operations
    - metadata
    - collections
    - overlays

plex:
  url: http://plex.media.svc.cluster.local:32400
  token: <<PLEX_API_KEY>>
  timeout: 120
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl: false

tautulli:
  url: http://tautulli.media.svc.cluster.local:8181
  apikey: <<TAUTULLI_API_KEY>>

tmdb:
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60

omdb:
  apikey: <<OMDB_API_KEY>>
  cache_expiration: 60

mdblist:
  apikey: <<MDBLIST_APIKEY>>
  cache_expiration: 60

radarr:
  url: http://radarr.media.svc.cluster.local:7878
  token: <<RADARR_API_KEY>>
  add_missing: false
  add_existing: false
  root_folder_path: /data/movies
  monitor: true
  availability: announced
  quality_profile: Any
  search: false
  upgrade_existing: false

sonarr:
  url: http://sonarr.media.svc.cluster.local:8989
  token: <<SONARR_API_KEY>>
  add_missing: false
  add_existing: false
  root_folder_path: /data/tv
  monitor: all
  quality_profile: Any
  language_profile: English
  series_type: standard
  season_folder: true
  search: false
  cutoff_search: false
  upgrade_existing: false
