kind: Secret
ansible_user: ENC[AES256_GCM,data:x9J3FGRyIQ==,iv:VYkzlgzRJD3YmfxGmBop0UGwE+NV5fEr4x6t/rXEzfk=,tag:kDn+8/PvcgYtBiKDuAVHFg==,type:str]
cloudflare_email: ENC[AES256_GCM,data:oK3VJR1vMhCCxLj+z0RsPjmboXTtEg==,iv:0O/Pin3yqdurAqKNNz9jApomwDRefy0Cixrm+TAu7JI=,tag:HrzZu+/M3QSoT4yYGYtQnw==,type:str]
cloudflare_password: ENC[AES256_GCM,data:grv+RUI/JIYcQYEWTk811t5lT9/O7464XAV7iqY0dkmFTWkAWQ==,iv:Uk56O6McIpRzVnorgti/nT42cM5CYOsnysV4woRNlOo=,tag:XEAHWSqLvvcJXt8n3DA6xw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:VMnXmFNFzcazp6x4d7SqWKlg5Q0=,iv:pA0Hx7vduQyHzq/OBfAaT0lXCqSEx7aGgc45hvoKir4=,tag:uU2QO696OFu+C/lDC1xIew==,type:str]
cluster_domain: ENC[AES256_GCM,data:oDl9pLIGTZYBHw==,iv:aNIQ/V8epvdP9RXixd7hwTPptSd+LmbI+iUStWWG01A=,tag:vdQudCbS8W5aSpC3FucfCQ==,type:str]
personal_domain: ENC[AES256_GCM,data:n/APCPy9pKLtGg==,iv:yUuJrNIg5oYSFFVNMsG7JPPAFDQOEnlykXG3t7GuVBk=,tag:kDAzm7/gpfCdlgFDPoJCSA==,type:str]
internal_domain: ENC[AES256_GCM,data:L84G12qwk0I=,iv:KioHJYRRio2c7AM1nmccoNL02KPHOdatfHyajwkh9Z0=,tag:TqA+dU9KdtuH9+e/1rtPFA==,type:str]
admin_user: ENC[AES256_GCM,data:DORzVkY=,iv:ak8zyAIyQq5PJOEZ10h/hBWIoUJOKgbSfFp63aV6Ow4=,tag:+ivOIk7xGEVi6x3waah38g==,type:str]
admin_password: ENC[AES256_GCM,data:ClsEMNYdr+fqLjW2HiZek/ft9lSMvktfEtJi0hQyYIfVDeXGiMR12lyD3xppehsh2Jr+Kdd9xi6sZvic,iv:ojIN0zowSOdx3k+qOcyHAdonvdH+s39VncHElZvTcbg=,tag:TQbCjrYdv2tvC5TShMjJKQ==,type:str]
uptime_kuma_ping_url: ENC[AES256_GCM,data:f++KPvhRi28LOJUXWUYWZQqRG/SBzIjdaRaysQssTo/ReWu99BQHiWP16PcQwXl4/+tcAxhQPOqDqYnNf2R9rsX11D8=,iv:V7l8B6GhKCw70L92Cj/fQXY1fQ3IIC750TVGq61iV9k=,tag:0VcSksM0hwJ8qpNYkq9CPA==,type:str]
wireguard_private_key: ENC[AES256_GCM,data:/TzkiLUSyVgR7GG2IlMi8vjwCo68ILrN8kPtJpm74SoP5v4wiOJaiTdu6kA=,iv:FnXW/BmWS2otDEj0E79P9De1t/LpOKzd4YZmemWd5LE=,tag:YtJ0OioS9IjC2oDS6XCqZw==,type:str]
edgeos_user_name: ENC[AES256_GCM,data:kxzyH28dYg==,iv:aFILph3rKn6bHd/abWFiCxEPa3vZn2t7MGMYIc/PUKU=,tag:oAZ2Uk8rdJJyN5nCCDeQuQ==,type:str]
edgeos_user_password: ENC[AES256_GCM,data:rNn+ndVqiqRH1AQonaddjq2+gClV0zhnRA+c2pjFn5VzB85pjjIe9wmVRAZJbjmP9ea+ttPzz6fpzqiLrJ4o,iv:4O0lZ82NEDe43oiXodQPY0oBmq5yYrKKn6LvKYWMXZQ=,tag:SOR1rkFo+CqHy4onQqvuEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1257acz7c2nyglyxaq6ulxwdndrkvl8u7tx84hqvq5qp04ekws38s20gzxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eTQrVEJ2QWlQT2pkMk9l
            aUNxdVJMeG9xVWVxQytya2t0UzdMdVNES0FJCkRIdFhBZ3dVV0p3Q1Zzenk3WTFq
            VUQrWmZHMUs2bG1PWnUyUXhqeExISkEKLS0tIHpkSUtXeGphMTlDZnZQdURkdmdT
            T2JEYWJ0WHV0ZjB5NWtJWWFrVTJyU28Kg+FbZpxhYP85UwBhPYKwQJi30WrRRhD9
            XFuyQjcXrlIPaJSOrHGh3s1iqGOAyr4C0/8ouyJVYO9sgX50kSvi2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-07T06:08:04Z"
    mac: ENC[AES256_GCM,data:D8OMnfM2R1/NH5iJjAgcxOZSxve3c71fa/mHOCdlieSA5RkT2rccCoczJCJG6R2svtPrGjf93PPRGEMH6768Zkw1BBrVYfI7T2XK+OxYsoTvXwEXMTl5N42meCtNYNJA5qVIIkAw89XgnoN3yMZlDmYHatu/YqCxXJ9lFjA04tQ=,iv:UaG4nJ2HaW88BQKqXMzmMwYl21QsQ9bee02eMZtbgoE=,tag:SBR9ilGA9z2tx1WjXbIUzA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
