---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: theme-headers
spec:
  # Set request headers to prioritize supported encoding.
  headers:
    customRequestHeaders:
      accept-encoding: gzip;1.0,deflate;0.5,identity;0.1

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: qbittorrent-headers
spec:
  # set CSP for qbittorrent, otherwise need to do manually in the application.
  headers:
    contentSecurityPolicy: default-src 'self'; style-src 'self' 'unsafe-inline' theme-park.${CLUSTER_DOMAIN} raw.githubusercontent.com use.fontawesome.com; img-src 'self' theme-park.${CLUSTER_DOMAIN} raw.githubusercontent.com data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self'; frame-ancestors 'self'; font-src use.fontawesome.com;
