---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - header-middleware.yaml

configMapGenerator:
  - name: traefik-middleware
    files:
      # Create header middleware dynamically using traefik go templates, instead of many CRDs
      - theme-park.yml=theme-park.go.tmpl
