---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - namespace.yaml
  - network-policy.yaml
  # Flux-Kustomizations
  - appdaemon/ks.yaml
  - authelia/ks.yaml
  - bazarr/ks.yaml
  - cloudnative-pg/ks.yaml
  - emqx/ks.yaml
  - esphome/ks.yaml
  - gaps/ks.yaml
  - glauth/ks.yaml
  - hajimari/ks.yaml
  - home-assistant/ks.yaml
  - immich/ks.yaml
  - jellyfin/ks.yaml
  - lidarr/ks.yaml
  - overseerr/ks.yaml
  - paperless/ks.yaml
  - plex/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - radarr-4k/ks.yaml
  - radicale/ks.yaml
  - recyclarr/ks.yaml
  - redis/ks.yaml
  - sabnzbd/ks.yaml
  - shlink/ks.yaml
  - smtp-relay/ks.yaml
  - sonarr/ks.yaml
  - tautulli/ks.yaml
  - theme-park/ks.yaml
  - unifi/ks.yaml
  - unpackerr/ks.yaml
  - vaultwarden/ks.yaml
  - zigbee2mqtt/ks.yaml
  - zwave-js-ui/ks.yaml
