---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./atuin/ks.yaml
  - ./authelia/ks.yaml
  - ./emqx/ks.yaml
  - ./esphome/ks.yaml
  - ./frigate/ks.yaml
  - ./home-assistant/ks.yaml
  - ./homepage/ks.yaml
  - ./homerp/ks.yaml
  - ./immich/ks.yaml
  - ./lldap/ks.yaml
  - ./matter-server/ks.yaml
  - ./paperless/ks.yaml
  - ./radicale/ks.yaml
  - ./saidcompany/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./teslamate/ks.yaml
  - ./thelounge/ks.yaml
  - ./windmill/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./zwave-js-ui/ks.yaml
