---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./atuin/ks.yaml
  - ./authelia/ks.yaml
  - ./cross-seed/ks.yaml
  - ./dashbrr/ks.yaml
  - ./displex/ks.yaml
  - ./emqx/ks.yaml
  - ./esphome/ks.yaml
  - ./frigate/ks.yaml
  - ./home-assistant/ks.yaml
  - ./homepage/ks.yaml
  - ./immich/ks.yaml
  - ./lldap/ks.yaml
  - ./paperless/ks.yaml
  - ./plex/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radicale/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./syncthing/ks.yaml
  - ./teslamate/ks.yaml
  - ./thelounge/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./zwave-js-ui/ks.yaml
