endpoints:
  - client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - '[STATUS] == ${GATUS_STATUS:=200}'
    group: external
    interval: 1m
    name: ${APP}
    url: https://${GATUS_SUBDOMAIN:=${APP}}.chestr.dev${GATUS_PATH:=/}
