---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/common
namespace: ai
resources:
  - ./ollama/ks.yaml
  - ./openweb-ui/ks.yaml
  - ./recommendarr/ks.yaml
