---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actions-runner-controller-auth-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # github_app_id, github_app_installation_id, github_app_private_key
        key: actions-runner-controller
