---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tracearr-secret
    creationPolicy: Owner
    template:
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        COOKIE_SECRET: "{{ .COOKIE_SECRET }}"
  dataFrom:
    - extract:
        key: tracearr
