---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-rewind
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plex-rewind-secret
    creationPolicy: Owner
    template:
      data:
        # NextAuth
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
  dataFrom:
    - extract:
        key: plex-rewind
