---
libraries:
  Movies:
    metadata_path:
      - pmm: tautulli
      - pmm: tmdb
      - pmm: basic
      - pmm: seasonal                                 # Christmas, Halloween, etc.
        template_variables:                           # Canadian Thankgsgiving is a different date range. Otherwise, I want to ALWAYS see the seasonal
          schedule_independence: daily
          schedule_easter: daily
          schedule_valentine: daily
          schedule_patrick: daily
          schedule_thanksgiving: range(10/01-10/31)
          schedule_halloween: daily
          schedule_christmas: daily
          schedule_years: daily
          schedule_mother: daily
          schedule_memorial: daily
          schedule_father: daily
          schedule_labor: daily
    overlay_path:
      - remove_overlays: false
      - pmm: streaming
      - pmm: ratings
      - pmm: ribbon
    operations:
      mass_genre_update: imdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_metacritic
      mass_user_rating_update: imdb

  TV Shows:
    metadata_path:
      - pmm: tautulli
      - pmm: tmdb
      - pmm: basic
      - pmm: seasonal                                 # Christmas, Halloween, etc.
        template_variables:                           # Canadian Thankgsgiving is a different date range. Otherwise, I want to ALWAYS see the seasonal
          schedule_independence: daily
          schedule_easter: daily
          schedule_valentine: daily
          schedule_patrick: daily
          schedule_thanksgiving: range(10/01-10/31)
          schedule_halloween: daily
          schedule_christmas: daily
          schedule_years: daily
          schedule_mother: daily
          schedule_memorial: daily
          schedule_father: daily
          schedule_labor: daily
    overlay_path:
      - remove_overlays: false
      - pmm: streaming
      - pmm: ratings
      - pmm: ribbon
    operations:
      mass_genre_update: tmdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_metacritic
      mass_user_rating_update: imdb
      mass_episode_audience_rating_update: mdb_tomatoesaudience
      mass_episode_critic_rating_update: mdb_metacritic
      mass_episode_user_rating_update: imdb

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: false
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: false
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_user:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users:

plex:
  url: http://plex.default.svc.cluster.local:32400
  token: <<PLEX_API_KEY>>
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false

tautulli:
  url: http://tautulli.default.svc.cluster.local:8181
  apikey: <<TAUTULLI_API_KEY>>

tmdb:
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60
  region:

omdb:
  apikey: <<OMDB_API_KEY>>
  cache_expiration: 60

mdblist:
  apikey: <<MDBLIST_API_KEY>>
  cache_expiration: 60

radarr:
  url: http://radarr.default.svc.cluster.local:7878
  token: <<RADARR_API_KEY>>
  add_missing: false
  add_existing: false
  root_folder_path: /media/movies
  monitor: true
  availability: announced
  quality_profile: Any
  tag:
  search: false
  radarr_path:
  plex_path:
  upgrade_existing: false

sonarr:
  url: http://sonarr.default.svc.cluster.local:8989
  token: <<SONARR_API_KEY>>
  add_missing: false
  add_existing: false
  root_folder_path: /media/tv
  monitor: all
  quality_profile: Any
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false

trakt:
  client_id: <<TRAKT_CLIENT_ID>>
  client_secret: <<TRAKT_CLIENT_SECRET>>
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope: public
    created_at:
  pin: <<TRAKT_PIN>>
