---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-snmp-exporter-edgerouter
  namespace: flux-system
spec:
  targetNamespace: monitoring
  path: ./kubernetes/apps/monitoring/exporters/snmp-exporter/edgerouter
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-snmp-exporter-lochnas
  namespace: flux-system
spec:
  targetNamespace: monitoring
  path: ./kubernetes/apps/monitoring/exporters/snmp-exporter/lochnas
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: false
