---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: plex-alerts
  labels:
    vmalert-logs.io/enabled: "true"
spec:
  groups:
    - name: &name PlexDatabaseBusy
      type: vlogs
      interval: 5m
      rules:
        - alert: *name
          expr: '"(?i)retry busy DB" | filter app := "plex" | count() rows | filter rows :> 0'
          annotations:
            description: '{{ $labels.app }} is experiencing database issues'
