---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - helmrelease.yaml
  - ../../../../templates/gatus/guarded
  - ../../../../templates/gatus/internal
configMapGenerator:
  - name: sonarr-pushover
    files:
      - ./scripts/pushover-notify.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
