---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: windmill
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Automation
    gethomepage.dev/name: Windmill
    gethomepage.dev/icon: windmill.png
    gatus.home-operations.com/endpoint: |
      conditions:
        - "[STATUS] == 200"
spec:
  hostnames:
    - windmill.chestr.dev
  parentRefs:
    - name: envoy-internal
      namespace: networking
      sectionName: https
  rules:
    - backendRefs:
        - name: windmill-app
          port: 8000
