---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: bazarr
  namespace: default
spec:
  sourcePVC: bazarr-config-v1
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    cacheCapacity: 1Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    repository: bazarr-restic-secret
    retain:
      daily: 10
