---
static_lan_ips:
  LochNas:
    ip_address: 192.168.1.128
    mac_address: 90:09:d0:03:83:ad
  OctoPrint:
    ip_address: 192.168.1.105
    mac_address: 00:1e:06:39:b3:13
  WiFi-AP:
    ip_address: 192.168.1.174
    mac_address: f4:92:bf:16:25:40
  sidero:
    ip_address: 192.168.1.195
    mac_address: 16:e2:77:16:cd:4c
  ender:
    ip_address: 192.168.1.190
    mac_address: 00:1e:06:42:f0:dc
  k8s-0:
    ip_address: 192.168.1.200
    mac_address: 18:60:24:26:58:6d
  k8s-1:
    ip_address: 192.168.1.201
    mac_address: ec:b1:d7:5c:55:90
  k8s-2:
    ip_address: 192.168.1.202
    mac_address: 00:25:22:b2:b4:f4
  k8s-3:
    ip_address: 192.168.1.203
    mac_address: 18:60:24:26:fd:f5
static_iot_ips:
  wled-WLED:
    ip_address: 10.0.10.54
    mac_address: 40:22:d8:7b:63:a4
  wled-WLED-Office:
    ip_address: 10.0.10.138
    mac_address: 40:22:d8:7b:56:ac
