---
static_lan_ips:
  LochNas:
    ip_address: 192.168.1.128
    mac_address: 90:09:d0:03:83:ad
    host: lochnas.chestr.dev
  WiFi-AP:
    ip_address: 192.168.1.174
    mac_address: f4:92:bf:16:25:40
  mainsail:
    ip_address: 192.168.1.190
    mac_address: 00:1e:06:39:b3:13
    host: mainsail.chestr.dev
  k8s-0:
    ip_address: 192.168.1.200
    mac_address: 18:60:24:26:58:6d
  k8s-1:
    ip_address: 192.168.1.201
    mac_address: ec:b1:d7:5c:55:90
  k8s-2:
    ip_address: 192.168.1.202
    mac_address: 00:25:22:b2:b4:f4
  k8s-3:
    ip_address: 192.168.1.203
    mac_address: 18:60:24:26:fd:f5
  k8s-4:
    ip_address: 192.168.1.204
    mac_address: e4:e7:49:52:fc:c2
  k8s-5:
    ip_address: 192.168.1.205
    mac_address: e4:e7:49:52:7d:bb
  k8s-6:
    ip_address: 192.168.1.206
    mac_address: d8:cb:8a:e6:2f:38
  pikvm:
    ip_address: 192.168.1.47
    mac_address: e4:5f:01:e1:58:4a
    host: pikvm.chestr.dev

static_iot_ips:
  doorbell:
    ip_address: 10.0.10.144
    mac_address: 9c:8e:cd:37:db:70
  livingroom_camera:
    ip_address: 10.0.10.164
    mac_address: 9c:95:61:90:a3:bb
  wled-WLED:
    ip_address: 10.0.10.54
    mac_address: 40:22:d8:7b:63:a4
  wled-WLED-Office:
    ip_address: 10.0.10.138
    mac_address: 40:22:d8:7b:56:ac
  home-controller:
    ip_address: 10.0.10.150
    mac_address: de:61:f6:ba:e3:98
    host: home-controller.chestr.dev
  k8s-0:
    ip_address: 10.0.10.200
    mac_address: 18:60:24:26:58:6d
  k8s-1:
    ip_address: 10.0.10.201
    mac_address: ec:b1:d7:5c:55:90
  k8s-2:
    ip_address: 10.0.10.202
    mac_address: 00:25:22:b2:b4:f4
  k8s-3:
    ip_address: 10.0.10.203
    mac_address: 18:60:24:26:fd:f5
  k8s-4:
    ip_address: 10.0.10.204
    mac_address: e4:e7:49:52:fc:c2
  k8s-5:
    ip_address: 10.0.10.205
    mac_address: e4:e7:49:52:7d:bb
  k8s-6:
    ip_address: 10.0.10.206
    mac_address: d8:cb:8a:e6:2f:38
