---
collections:
  - name: community.general
    version: 6.1.0
  - name: community.sops
    version: 1.5.0
  - name: ansible.posix
    version: 1.4.0
  - name: ansible.utils
    version: 2.8.0
roles:
  - name: semuadmin.octoprint
    src: https://github.com/semuconsulting/ansible_octoprint
    version: master
