---
collections:
  - name: community.general
    version: 8.2.0
  - name: community.sops
    version: 1.6.7
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 3.0.0
roles:
  - name: semuadmin.octoprint
    src: https://github.com/semuconsulting/ansible_octoprint
    version: master
