---
collections:
  - name: community.general
    version: 7.0.0
  - name: community.sops
    version: 1.6.1
  - name: ansible.posix
    version: 1.5.2
  - name: ansible.utils
    version: 2.9.0
roles:
  - name: semuadmin.octoprint
    src: https://github.com/semuconsulting/ansible_octoprint
    version: master
