---
collections:
  - name: community.general
    version: 7.5.1
  - name: community.sops
    version: 1.6.6
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.11.0
roles:
  - name: semuadmin.octoprint
    src: https://github.com/semuconsulting/ansible_octoprint
    version: master
