---
collections:
  - name: community.general
    version: 9.5.0
  - name: community.sops
    version: 2.0.0
  - name: ansible.posix
    version: 1.6.1
  - name: ansible.utils
    version: 5.1.2
roles:
  - name: semuadmin.octoprint
    src: https://github.com/semuconsulting/ansible_octoprint
    version: master
