---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app radarr-4k
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radarr-4k-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RADARR__AUTH__APIKEY: "{{ .RADARR_4K_API_KEY }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        PUSHOVER_TOKEN: "{{ .PUSHOVER_RADARR_4K_TOKEN }}"
  dataFrom:
    - extract:
        key: *app
    - extract:
        key: pushover
