---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-debug
spec:
  containers:
    - name: debug
      image: docker.io/library/ubuntu:24.04
      command: ["/bin/bash", "-c", "apt-get update && apt-get install -y rsync && sleep infinity"]
      volumeMounts:
        - name: nebula
          mountPath: /mnt/nebula
        - name: lochnas
          mountPath: /mnt/lochnas
  volumes:
    - name: nebula
      nfs:
        server: nebula.chestr.dev
        path: /var/nfs/shared/cluster
    - name: lochnas
      nfs:
        server: lochnas.chestr.dev
        path: /volume1/shared
