---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: radarr-rules
  namespace: default
spec:
  groups:
    - name: radarr.rules
      rules:
        - alert: RadarrQueueItems
          expr: radarr_queue_total AND changes(radarr_queue_total[1h]) == 0
          for: 4h
          labels:
            severity: warning
          annotations:
            summary: "Radarr may have items stuck in the queue (instance {{ $labels.instance }})"
            description: "Radarr queue hasn't changed for more than 1 hour\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
