---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &app home-assistant
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *app
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Home Assistant
        HASS_COUNTRY: CA
        HASS_PROVINCE: BC
        HASS_DATABASE_URL: postgresql://{{ .HASS_STORAGE_POSTGRES_USERNAME }}:{{ .HASS_STORAGE_POSTGRES_PASSWORD }}@postgres-rw.default.svc.cluster.local/home-assistant
        HASS_GOOGLE_CLIENT_ID: "{{ .HASS_GOOGLE_CLIENT_ID }}"
        HASS_GOOGLE_CLIENT_SECRET: "{{ .HASS_GOOGLE_CLIENT_SECRET }}"
        HASS_GOOGLE_PUBSUB_TOPIC: "{{ .HASS_GOOGLE_PUBSUB_TOPIC }}"
        HASS_GOOGLE_PROJECT_ID: "{{ .HASS_GOOGLE_PROJECT_ID }}"
        HASS_GOOGLE_ASSISTANT_PROJECT_ID: "{{ .HASS_GOOGLE_ASSISTANT_PROJECT_ID }}"
        HASS_CAT_CAMERA_STREAM_SOURCE: "{{ .HASS_CAT_CAMERA_STREAM_SOURCE }}"
        HASS_CAT_CAMERA_DEVICE_ID: "{{ .HASS_CAT_CAMERA_DEVICE_ID }}"
        HASS_ALARM_CONTROL_PANEL_CODE: "{{ .HASS_ALARM_CONTROL_PANEL_CODE }}"
        HASS_WASTE_COLLECTION_SCHEDULE_ICS_URL: "{{ .HASS_WASTE_COLLECTION_SCHEDULE_ICS_URL }}"
        # Postgres Init
        POSTGRES_DB: *app
        POSTGRES_HOST: postgres-rw.default.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .HASS_STORAGE_POSTGRES_PASSWORD }}"
        POSTGRES_USER: "{{ .HASS_STORAGE_POSTGRES_USERNAME }}"
  dataFrom:
    - extract:
        key: *app
    - extract:
        key: cloudnative-pg
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &app home-assistant-deploykey
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *app
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        id_rsa.pub: "{{ .HASS_PUBLIC_DEPLOYKEY }}"
        id_rsa: "{{ .HASS_DEPLOYKEY }}"
  dataFrom:
    - extract:
        key: home-assistant
