---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-system.yaml
  - cert-manager.yaml
  - csi-driver-nfs.yaml
  - database-system.yaml
  - game-system.yaml
  - home.yaml
  - kubernetes-dashboard.yaml
  - longhorn-system.yaml
  - media.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - networking.yaml
  - system-upgrade.yaml
