---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-system.yaml
  - databases.yaml
  - home.yaml
  - kyverno.yaml
  - media.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - networking.yaml
  - rook-ceph.yaml
