---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-auth
spec:
  chain:
    middlewares:
      - name: internal
      - name: security
        namespace: auth-system
